config/routes.rb
FavTabs::Application.routes.draw do

  constraints(:host => "www.convorum.com") do
    match "(*x)" => redirect { |params, request|
      URI.parse(request.url).tap { |x| x.host = "convorum.com" }.to_s
    }
  end 
  match "discussions/create_multiple_discussion"  => "discussions#create_multiple_discussion"
  match "discussion_groups/create_multiple_discussion"  => "discussion_groups#create_multiple_discussion"
  match "discussions/post_multiple_comments"  => "discussions#post_multiple_comments"
  match "discussions/save_multiple_comments"  => "discussions#save_multiple_comments"
  resources :albums

  resources :profile_pictures

  resources :ratings

  resources :comments

  resources :user_discussions

  resources :follower_followings
  match "discussions/updates_from_following_follower" => "discussions#updates_from_following_follower"
  resources :messages
  match 'new_message' => 'messages#new_message'
  match 'sent_messages' => 'messages#sent_messages'
  match 'message_delete' => 'messages#message_delete'
  match 'from_follower_following' => 'messages#from_follower_following'
  resources :tab_sites

  resources :tabs

  resources :user_details
  match 'logins/create' => 'logins#create'
  match 'logins/activate/:id' => 'logins#activate'
  match 'logins/forgot_password' => 'logins#forgot_password'
  match 'login' => 'logins#login'
  match 'logout' => 'logins#logout'
  match 'test_remote_call' => 'users#test_remote_call'

  match 'users/edit_profile_picture' => 'users#edit_profile_picture'
  match 'load_more_search_result' => 'users#load_more_search_result'

  match 'about_us' => 'logins#about_us'
  match 'contact_us' => 'logins#contact_us'

  match "users/profile/:id"  => "users#my_account"

  match 'users/followers/:id' => 'users#followers'
  match 'users/followings/:id' => 'users#followings'
  match 'users/follow/:id' => 'users#follow'
  match 'users/set_email_updates/:id' => 'users#set_email_updates'
  match 'follower_following_delete/:id' => 'users#follower_following_delete'

  match "users/add_tab"  => "users#add_tab"
  match "users/add_current_tab"  => "users#add_current_tab"
  match "users/edit_tab"  => "users#edit_tab"
  match "users/delete_tab"  => "users#delete_tab"
  match "users/delete_site_url"  => "users#delete_site_url"
  match "users/edit_site_url"  => "users#edit_site_url"
  match "users/create_site"  => "users#create_site"
  match "users/find_people" => "users#find_people"
  match "users/manage_groups" => "users#manage_groups"
  match "users/create_group" => "users#create_group"
  match "users/edit_group" => "users#edit_group"
  match "users/add_email" => "users#add_email"
  match "users/add_email_to_crowd/:id" => "users#add_email_to_crowd"
  match "users/import_gmail_contacts/:id" => "users#import_gmail_contacts"

  match "users/delete_group" => "users#delete_group"

  match "albums/create_album" => "albums#create_album"
  match "albums/edit_album" => "albums#edit_album"
  match "albums/delete_album/:id" => "albums#delete_album"
  match "share_album_in_group/:id" => "albums#share_album_in_group"
  match "share_photo_in_group/:id" => "albums#share_photo_in_group"
  match "albums/create_multiple_photos" => "albums#create_multiple_photos"
  match "albums/save_multiple_photos" => "albums#save_multiple_photos"

  match "find_photo" => "albums#find_photo"
  match "add_photo" => "albums#add_photo"
  match "add_photos_from_site" => "albums#add_photos_from_site"
  match "load_my_groups" => "albums#load_my_groups"
  match "add_photo_from_system" => "albums#add_photo_from_system"
  match "load_photos_discussions" => "albums#load_photos_discussions"
  match "load_album_photos/:id" => "albums#load_album_photos"
  
  match "users/set_tab_private/:id"  => "users#set_tab_private"
  match "users/set_tab_public/:id"  => "users#set_tab_public"
  match "share_with_group/:id"  => "users#share_with_group"
  match "add_to_group/:id"  => "users#add_to_group"
  match "non_site_add_to_crowd/:id"  => "users#non_site_add_to_crowd"

  match "remove_from_group/:id"  => "users#remove_from_group"
  match "remove_non_site_from_crowd/:id"  => "users#remove_non_site_from_crowd"
  
  resources :discussions
  match "discussions/create_discussion"  => "discussions#create_discussion"

  match "discussions/add_title_discription"  => "discussions#add_title_discription"
  match "discussions/add_title_discription/:id"  => "discussions#add_title_discription"
  match "discussions/save_multiple_discussion"  => "discussions#save_multiple_discussion"
  match "discussions/return_to_previous/:id"  => "discussions#return_to_previous"
  match "discussions/updates_from_following_follower" => "discussions#updates_from_following_follower"
  match "discussions/post_comments"  => "discussions#post_comments"
  match "discussions/join_discussion/:id"  => "discussions#join_discussion"
  match "load_comments/:id"  => "discussions#load_comments"
  match "load_my_comments/:id"  => "discussions#load_my_comments"
  match "load_my_discussions/:id"  => "discussions#load_my_discussions"
  match "load_my_discussions_on_scroll"  => "discussions#load_my_discussions_on_scroll"
  match "load_most_pop_discussions_on_scroll"  => "discussions#load_most_pop_discussions_on_scroll"

  match "discussions/web_content/:id"  => "discussions#web_content"

  match "discussions/post_multiple_comment_responses"  => "discussions#post_multiple_comment_responses"
  match "discussions/post_comment_responses"  => "discussions#post_comment_responses"
  match "all_discussion" => "discussions#all_discussion"
  match "all_discussion" => "discussions#all_discussion"
  match "load_discussion_as_per_time/:id" => "discussions#load_discussion_as_per_time"
  match "discussions/update_comment_responses" => "discussions#update_comment_responses"
  match "delete_comment/:id" => "discussions#delete_comment"
  match "delete_discussion/:id" => "discussions#delete_discussion"
  match "search_user_names_for_message/:term" => "users#search_user_names_for_message"
  match "show_discussion/:id" => "discussions#show_discussion"
  match "load_my_comments_on_scroll" => "discussions#load_my_comments_on_scroll"
  match "load_more_feeds" => "discussions#load_more_feeds"

  match "albums/index/:id"  => "albums#index"
  match "find_photo" => "albums#find_photo"
  match "add_photo" => "albums#add_photo"
  match "add_photos_from_site" => "albums#add_photos_from_site"
  match "load_my_groups" => "albums#load_my_groups"
  match "load_photo_full_detail/:id" => "albums#load_photo_full_detail"
  match "like_picture/:id" => "albums#like_picture"
  match "unlike_picture/:id" => "albums#unlike_picture"
  match "delete_picture/:id" => "albums#delete_picture"
  match "post_photo_comment" => "albums#post_photo_comment"
  match "delete_picture_comment/:id" => "albums#delete_picture_comment"
  match "import_picture/:id" => "albums#import_picture"
  match "photo_discussions" => "albums#photo_discussions"
  match "upload_photos" => "albums#create_multiple_albums"

  match "discussion_groups/import_picture/:id" => "discussion_groups#import_picture"
  match "discussion_groups/delete_picture/:id" => "discussion_groups#delete_picture"
  match "discussion_groups/delete_picture_comment/:id" => "discussion_groups#delete_picture_comment"
  match "discussion_groups/post_photo_comment" => "discussion_groups#post_photo_comment"
  match "discussion_groups/load_photo_full_detail/:id" => "discussion_groups#load_photo_full_detail"
  match "discussion_groups/load_pictures/:id" => "discussion_groups#load_pictures"
  match "discussion_groups/like_picture/:id" => "discussion_groups#like_picture"
  match "discussion_groups/unlike_picture/:id" => "discussion_groups#unlike_picture"
  match "discussion_groups/add_photo_from_system" => "discussion_groups#add_photo_from_system"
  match "discussion_groups/add_photo" => "discussion_groups#add_photo"
  match "discussion_groups/group_album/:id" => "discussion_groups#group_album"
  match "discussion_groups/create_discussion" => "discussion_groups#create_discussion"
  match "discussion_groups/create_discussion_group" => "discussion_groups#create_discussion_group"
  match "edit_discussion_group/:id" => "discussion_groups#edit_discussion_group"
  match "discussion_groups/delete_discussion_group/:id" => "discussion_groups#delete_discussion_group"
  match "discussion_groups/search_groups/" => "discussion_groups#search_groups"
  match "discussion_groups/add_user_to_groups/:id" => "discussion_groups#add_user_to_groups"
  match "discussion_groups/invite_user_to_groups/:id" => "discussion_groups#invite_user_to_groups"
  match "load_more_groups/:search_text" => "discussion_groups#load_more_groups"
  match "search_for_group/:term" => "users#search_for_group"
  match "notifications/:id" => "discussion_groups#notifications"
  match "accept_invitation/:id" => "discussion_groups#accept_invitation"
  match "decline_invitation/:id" => "discussion_groups#decline_invitation"
  match "join_group/:id" => "discussion_groups#join_group"
  match "unjoin_group/:id" => "discussion_groups#unjoin_group"
  match "leave_joined_group/:id" => "discussion_groups#leave_joined_group"
  match "discussions/load_feeds_by_group/:id" => "discussions#load_feeds_by_group"
  match "load_group_discussion/:id" => "discussions#load_group_discussion"
  match "load_group_discussions_on_scroll/:id" => "discussion_groups#load_group_discussions_on_scroll"

  match "discussion_groups/delete_added_group_user/:id" => "discussion_groups#delete_added_group_user"
  match "discussion_groups/edit_added_group_user/:id" => "discussion_groups#edit_added_group_user"

  match 'discussion_groups/invite_emails_to_group/:id' => 'discussion_groups#invite_emails_to_group'
  match 'discussion_groups/import_gmail_contacts/:id' => 'discussion_groups#import_gmail_contacts'

  resources :discussion_groups do
    collection do
      get 'search_groups'
    end
  end

  match "logins/invitation_sign_up/:id" => "logins#invitation_sign_up"
  resources :users do

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => 'User', :foreign_key => 'sender_id'
  belongs_to :recipient, :class_name => 'User', :foreign_key => 'receiver_id'
  
  validates :message, :presence => true, :length => {:maximum => 2000}
  validates :receiver_id, :presence => true# {:message => 'Please select the receiver.'}
  #--                                                    
  #
  #Created on: 07/01/2012
  #Purpose: 
  #++ This method is used to delete the message by sender/receiver
  after_validation :validate_message_sender


  def validate_message_sender
    self.errors.add :receiver_id, "can not be sender." if self.sender_id==self.receiver_id
  end

  def delete_message(user_id)
    var = user_id == self.sender_id ? "sender" : "receiver"
    self.update_attribute("deleted_by_#{var}", true)
  end


end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sender_id %><br />
    <%= f.text_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :receiver_id %><br />
    <%= f.text_field :receiver_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :deleted_by_sender %><br />
    <%= f.check_box :deleted_by_sender %>
  </div>
  <div class="field">
    <%= f.label :deleted_by_receiver %><br />
    <%= f.check_box :deleted_by_receiver %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_reply_msg.html.erb
<%= javascript_include_tag 'message' %> 
<%= form_for(@message, :remote => true) do |f| %>
  <%= f.hidden_field :receiver_ids, :value => get_username(message.sender_id) %>
  <%= f.hidden_field :sender_id, :value => current_user.id %>
  <%= f.text_area :message, :id => "message_message", :class => "reply_message_text_area"  %>
  <span id="msg_error" class="form_error">&nbsp;</span>
  <%= f.submit "Send", :class => "blue_btn float_l margin_top_five", :onclick => "return set_current_object(#{message.id})" %>
<% end %>

app/views/messages/create.js.erb
display_flash_message("<%=  @message.nil? ? "The user is not present." : (@message.errors.present? ? @message.errors.full_messages.to_sentence : 'Message sent successfully.')  %>");
<% if !@message.errors.present? %>
jQuery(".reply_message_text_area").val("");
jQuery("#recievers_text_box").val("");
jQuery("#message_message").val("");
<% end %>
jQuery("#reply_msg_box_"+curr_object).hide();
jQuery("#reply_msg_box_"+curr_object).prev().children(".message_action_div").children("a.reply_link").html("Reply");

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<script type="text/javascript">
  var curr_object;
  jQuery(document).ready(function(){

    jQuery("#inbox_div").children(".menu_item ").addClass("current_menu");


    /*for css*/
    doc_ht = jQuery(document).height();
    jQuery(".background_wrapper").css('height',doc_ht+'px');
    if(jQuery.browser.opera)
    {
      jQuery(".blue_btn").css('padding-bottom','2px');
    }
    /* UI Functionality */
    /* For toggling reply section */
    jQuery(".reply_link").click(function(){
      current_link = jQuery(this);
      if(current_link.html()=="Reply")
      {
        current_link.html("Cancel");
        current_link.parent().parent().parent().find(".reply_message_form_div").slideDown();
      }
      else
      {
        current_link.html("Reply");
        current_link.parent().parent().parent().find(".reply_message_form_div").slideUp();
      }
      return false;
    });

    /* For toggling message sections*/
    
    $('.delete_msg').bind('ajax:success', function() {
      $(this).closest('tr').fadeOut();
    });

  });

  function set_current_object(curr_obj)
  {
    curr_object = curr_obj;
  }

</script>
<div class="main_panel">
  <span class="blue_header">Messages</span>
  <!-- Message conatiner satart here -->
  <div class="messages_conatiner inbox_div">
    <% if !@received_msgs.blank? %>
      <table>
        <% @received_msgs.each do |message| %>
          <tr><td>
              <!-- message 1 -->
              <div class="inbox_message">
                <div class="user_image_div">
                  <a href="<%= message.sender.is_admin? ? '#': get_user_by_user_id(message.sender_id).profile_path %>" class="user_name">
                    <img alt="" class="medium_user_image" src="<%= get_user_by_user_id(message.sender_id).profile_pic(:medium) %>" /></a>
                </div>
                <div class="message_div">
                  <a href="<%= message.sender.is_admin? ? '#':get_user_by_user_id(message.sender_id).profile_path %>" class="user_name">
                    <% if message.sender.is_admin? %>
                      System Message
                    <%else %>
                      <%= message.sender.username %>
                    <% end %>
                  </a>
                  <span class="message_date_time">Received at <%= message_time(message) %></span>
                  <span class="message_detail">
                    <pre class="message_pre"><%= message.message %></pre>
                  </span>
                  <div class="message_action_div">
                    <% unless message.sender.is_admin? %>
                      <a href="#" class="discussion_action_link reply_link">Reply</a>
                      <span class="spacer">&nbsp;</span>
                    <% end %>
                    <%=  link_to 'Delete', {:action => 'message_delete', :id => message.id }, :confirm=>"Are you sure you want to delete?", :remote=>true, :class => "discussion_action_link delete_msg" %>
                  </div>
                </div>
                <% unless message.sender.is_admin? %>
                  <div class="reply_message_form_div" id="reply_msg_box_<%= message.id %>">
                    <%= render 'reply_msg', :message => message %>
                  </div>
                <% end %>
              </div>
            </td></tr>
        <% end %>
        <%= will_paginate @received_msgs %>
      </table>
    <% else  %>
      You have no messages.
    <% end %>
  </div>
</div>
<!-- end message -->
<!-- Message conatiner end here -->

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/new_message.html.erb
<script type="text/javascript">

  jQuery(document).ready(function() {
    jQuery("#new_message_div").children(".menu_item ").addClass("current_menu");
	
    jQuery('#receiver_id').keyup(function() {
      $('#message_receiver_id').val('')
    });

    jQuery('#from_follower_following').click(function() {
      $.ajax({
  	url: "from_follower_following",
        success: function(){
          $('#message_receiver_id').val('');
          $('#receiver_id').val('');
  	}
      });
    });

  });

</script>
<script type="text/javascript" src="/javascripts/message.js"></script>
<div class="main_panel">
  <span class="blue_header">New Message</span>
  <div id="new_message_error">&nbsp;</div>
  <%= form_for(@message, :remote => true) do |f| %>


    <%= f.hidden_field :sender_id, :value => current_user.id %>
    <%= f.hidden_field :receiver_id, :value => '' %>
    <!--input type="submit" class="blue_btn float_l margin_top_five" value="Send" /-->

    <!-- Message conatiner satart here -->
    <div class="messages_conatiner new_message_div">
      <div class="form_fields_div">
        <span class="form_left_data form_field_name float_l">To:<span class="mendatory">*</span></span>
        <span class="form_right_data form_field_control float_l">
          <%#= autocomplete_field_tag "receiver_id", '', autocomplete_user_username_users_path, :id_element => '#id_element', :class => "" %>
          <input type="text" name="message[receiver_ids]" id="recievers_text_box" class="new_message_text_field float_l"/>
          <span class="new_message_select_from_f_n_f">
            <% unless @login_user.is_admin? %>
            <input type="checkbox" class="float_l" id="from_follower_following"/> <span class="margin_top_five">Select from your followings and followers</span></span>
            <% end %>
           <span id="to_error" class="form_error clear_both">&nbsp;</span>
        </span>
        
      </div>
      <div class="form_fields_div">
        <span class="form_left_data form_field_name float_l">Message:<span class="mendatory">*</span></span>
        <span class="form_right_data form_field_control float_l">
          <%= f.text_area :message,:id => "message_message", :class=>"new_message_text_area" %>
        <span id="msg_error" class="form_error clear_both">&nbsp;</span>
        </span>
        
      </div>
      <div class="form_fields_div">
        <span class="form_left_data form_field_name float_l">&nbsp;</span>
        <span class="form_right_data form_field_control float_l">
          <%= f.submit "Send", :class => "blue_btn", :onclick => "return checkMessageValidation()" %>
        </span>
      </div>



    </div>
  <% end %>
  <!-- Message conatiner end here -->
</div>
<script type="text/javascript">
  
 jQuery(document).ready(function(){

	

function split( val ) {
			return val.split( /,\s*/ );
		}
		function extractLast( term ) {
			return split( term ).pop();
		}

		$( "#recievers_text_box" )
			// don't navigate away from the field on tab when selecting an item
			.bind( "keydown", function( event ) {
				if ( event.keyCode === $.ui.keyCode.TAB &&
						$( this ).data( "autocomplete" ).menu.active ) {
					event.preventDefault();
				}
			})
			.autocomplete({
				source: function( request, response ) {
					$.getJSON( "search_user_names_for_message/"+extractLast( request.term ),response );
				},
				search: function() {
					// custom minLength
					var term = extractLast( this.value );
					if ( term.length < 1 ) {
						return false;
					}
				},
				focus: function() {
					// prevent value inserted on focus
					return false;
				},
				select: function( event, ui ) {

					var terms = split( this.value );
					// remove the current input
					terms.pop();
					// add the selected item
                                        if(this.value.indexOf(ui.item.value+",")==-1)
                                        {
                                          terms.push( ui.item.value );
                                        }
					// add placeholder to get the comma-and-space at the end
					terms.push( "" );
					this.value = terms.join( ", " );
					return false;
				}
			});





}); 



</script>

app/views/messages/sent_messages.html.erb
<script type="text/javascript">
  jQuery(document).ready(function(){
   
    jQuery("#sent_message_div").children(".menu_item ").addClass("current_menu");
  
    $('.delete_msg').bind('ajax:success', function() {
      $(this).closest('tr').fadeOut();
    });
  });
</script>

<div style="width:280px" class="msg-td">
  <div style="width:280px" id="msgError">
  </div>
</div>

<div class="main_panel">
  <span class="blue_header">Sent Messages</span>

  <!-- Message conatiner satart here -->
  <div class="messages_conatiner sent_message_div">
    <% if !@sent_msgs.blank? %>
      <table>
        <% for message in @sent_msgs %>
          <tr><td>
              <!-- message 1 -->
              <div class="inbox_message">
                <div class="user_image_div">
                  <a href="<%= get_user_by_user_id(message.receiver_id).profile_path %>" class="user_name">
                    <img alt="" class="medium_user_image" src="<%= get_user_by_user_id(message.receiver_id).profile_pic(:medium) %>" /></a>
                </div>
                <div class="message_div">
                  <a href="<%= get_user_by_user_id(message.receiver_id).profile_path %>" class="user_name"><%= message.recipient.username %></a>
                  <span class="message_date_time">Sent at <%= message_time(message) %></span>
                  <span class="message_detail">
                    <pre class="message_pre"><%= message.message %></pre>
                  </span>
                  <div class="message_action_div">
                    <%=  link_to 'Delete', {:action => 'message_delete', :id => message.id }, :confirm=>"Are you sure you want to delete?", :remote=>true, :class => "discussion_action_link delete_msg" %>
                  </div>
                </div>
              </div>
            </td></tr>
        <% end %>
        <%= will_paginate @sent_msgs %>
      </table>
    <% else  %>
      You have no sent messages.
    <% end %>
  </div>
</div>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sender:</b>
  <%= @message.sender_id %>
</p>

<p>
  <b>Receiver:</b>
  <%= @message.receiver_id %>
</p>

<p>
  <b>Message:</b>
  <%= @message.message %>
</p>

<p>
  <b>Deleted by sender:</b>
  <%= @message.deleted_by_sender %>
</p>

<p>
  <b>Deleted by receiver:</b>
  <%= @message.deleted_by_receiver %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>