config/routes.rb
FavTabs::Application.routes.draw do

  constraints(:host => "www.convorum.com") do
    match "(*x)" => redirect { |params, request|
      URI.parse(request.url).tap { |x| x.host = "convorum.com" }.to_s
    }
  end 
  match "discussions/create_multiple_discussion"  => "discussions#create_multiple_discussion"
  match "discussion_groups/create_multiple_discussion"  => "discussion_groups#create_multiple_discussion"
  match "discussions/post_multiple_comments"  => "discussions#post_multiple_comments"
  match "discussions/save_multiple_comments"  => "discussions#save_multiple_comments"
  resources :albums

  resources :profile_pictures

  resources :ratings

  resources :comments

  resources :user_discussions

  resources :follower_followings
  match "discussions/updates_from_following_follower" => "discussions#updates_from_following_follower"
  resources :messages
  match 'new_message' => 'messages#new_message'
  match 'sent_messages' => 'messages#sent_messages'
  match 'message_delete' => 'messages#message_delete'
  match 'from_follower_following' => 'messages#from_follower_following'
  resources :tab_sites

  resources :tabs

  resources :user_details
  match 'logins/create' => 'logins#create'
  match 'logins/activate/:id' => 'logins#activate'
  match 'logins/forgot_password' => 'logins#forgot_password'
  match 'login' => 'logins#login'
  match 'logout' => 'logins#logout'
  match 'test_remote_call' => 'users#test_remote_call'

  match 'users/edit_profile_picture' => 'users#edit_profile_picture'
  match 'load_more_search_result' => 'users#load_more_search_result'

  match 'about_us' => 'logins#about_us'
  match 'contact_us' => 'logins#contact_us'

  match "users/profile/:id"  => "users#my_account"

  match 'users/followers/:id' => 'users#followers'
  match 'users/followings/:id' => 'users#followings'
  match 'users/follow/:id' => 'users#follow'
  match 'users/set_email_updates/:id' => 'users#set_email_updates'
  match 'follower_following_delete/:id' => 'users#follower_following_delete'

  match "users/add_tab"  => "users#add_tab"
  match "users/add_current_tab"  => "users#add_current_tab"
  match "users/edit_tab"  => "users#edit_tab"
  match "users/delete_tab"  => "users#delete_tab"
  match "users/delete_site_url"  => "users#delete_site_url"
  match "users/edit_site_url"  => "users#edit_site_url"
  match "users/create_site"  => "users#create_site"
  match "users/find_people" => "users#find_people"
  match "users/manage_groups" => "users#manage_groups"
  match "users/create_group" => "users#create_group"
  match "users/edit_group" => "users#edit_group"
  match "users/add_email" => "users#add_email"
  match "users/add_email_to_crowd/:id" => "users#add_email_to_crowd"
  match "users/import_gmail_contacts/:id" => "users#import_gmail_contacts"

  match "users/delete_group" => "users#delete_group"

  match "albums/create_album" => "albums#create_album"
  match "albums/edit_album" => "albums#edit_album"
  match "albums/delete_album/:id" => "albums#delete_album"
  match "share_album_in_group/:id" => "albums#share_album_in_group"
  match "share_photo_in_group/:id" => "albums#share_photo_in_group"
  match "albums/create_multiple_photos" => "albums#create_multiple_photos"
  match "albums/save_multiple_photos" => "albums#save_multiple_photos"

  match "find_photo" => "albums#find_photo"
  match "add_photo" => "albums#add_photo"
  match "add_photos_from_site" => "albums#add_photos_from_site"
  match "load_my_groups" => "albums#load_my_groups"
  match "add_photo_from_system" => "albums#add_photo_from_system"
  match "load_photos_discussions" => "albums#load_photos_discussions"
  match "load_album_photos/:id" => "albums#load_album_photos"
  
  match "users/set_tab_private/:id"  => "users#set_tab_private"
  match "users/set_tab_public/:id"  => "users#set_tab_public"
  match "share_with_group/:id"  => "users#share_with_group"
  match "add_to_group/:id"  => "users#add_to_group"
  match "non_site_add_to_crowd/:id"  => "users#non_site_add_to_crowd"

  match "remove_from_group/:id"  => "users#remove_from_group"
  match "remove_non_site_from_crowd/:id"  => "users#remove_non_site_from_crowd"
  
  resources :discussions
  match "discussions/create_discussion"  => "discussions#create_discussion"

  match "discussions/add_title_discription"  => "discussions#add_title_discription"
  match "discussions/add_title_discription/:id"  => "discussions#add_title_discription"
  match "discussions/save_multiple_discussion"  => "discussions#save_multiple_discussion"
  match "discussions/return_to_previous/:id"  => "discussions#return_to_previous"
  match "discussions/updates_from_following_follower" => "discussions#updates_from_following_follower"
  match "discussions/post_comments"  => "discussions#post_comments"
  match "discussions/join_discussion/:id"  => "discussions#join_discussion"
  match "load_comments/:id"  => "discussions#load_comments"
  match "load_my_comments/:id"  => "discussions#load_my_comments"
  match "load_my_discussions/:id"  => "discussions#load_my_discussions"
  match "load_my_discussions_on_scroll"  => "discussions#load_my_discussions_on_scroll"
  match "load_most_pop_discussions_on_scroll"  => "discussions#load_most_pop_discussions_on_scroll"

  match "discussions/web_content/:id"  => "discussions#web_content"

  match "discussions/post_multiple_comment_responses"  => "discussions#post_multiple_comment_responses"
  match "discussions/post_comment_responses"  => "discussions#post_comment_responses"
  match "all_discussion" => "discussions#all_discussion"
  match "all_discussion" => "discussions#all_discussion"
  match "load_discussion_as_per_time/:id" => "discussions#load_discussion_as_per_time"
  match "discussions/update_comment_responses" => "discussions#update_comment_responses"
  match "delete_comment/:id" => "discussions#delete_comment"
  match "delete_discussion/:id" => "discussions#delete_discussion"
  match "search_user_names_for_message/:term" => "users#search_user_names_for_message"
  match "show_discussion/:id" => "discussions#show_discussion"
  match "load_my_comments_on_scroll" => "discussions#load_my_comments_on_scroll"
  match "load_more_feeds" => "discussions#load_more_feeds"

  match "albums/index/:id"  => "albums#index"
  match "find_photo" => "albums#find_photo"
  match "add_photo" => "albums#add_photo"
  match "add_photos_from_site" => "albums#add_photos_from_site"
  match "load_my_groups" => "albums#load_my_groups"
  match "load_photo_full_detail/:id" => "albums#load_photo_full_detail"
  match "like_picture/:id" => "albums#like_picture"
  match "unlike_picture/:id" => "albums#unlike_picture"
  match "delete_picture/:id" => "albums#delete_picture"
  match "post_photo_comment" => "albums#post_photo_comment"
  match "delete_picture_comment/:id" => "albums#delete_picture_comment"
  match "import_picture/:id" => "albums#import_picture"
  match "photo_discussions" => "albums#photo_discussions"
  match "upload_photos" => "albums#create_multiple_albums"

  match "discussion_groups/import_picture/:id" => "discussion_groups#import_picture"
  match "discussion_groups/delete_picture/:id" => "discussion_groups#delete_picture"
  match "discussion_groups/delete_picture_comment/:id" => "discussion_groups#delete_picture_comment"
  match "discussion_groups/post_photo_comment" => "discussion_groups#post_photo_comment"
  match "discussion_groups/load_photo_full_detail/:id" => "discussion_groups#load_photo_full_detail"
  match "discussion_groups/load_pictures/:id" => "discussion_groups#load_pictures"
  match "discussion_groups/like_picture/:id" => "discussion_groups#like_picture"
  match "discussion_groups/unlike_picture/:id" => "discussion_groups#unlike_picture"
  match "discussion_groups/add_photo_from_system" => "discussion_groups#add_photo_from_system"
  match "discussion_groups/add_photo" => "discussion_groups#add_photo"
  match "discussion_groups/group_album/:id" => "discussion_groups#group_album"
  match "discussion_groups/create_discussion" => "discussion_groups#create_discussion"
  match "discussion_groups/create_discussion_group" => "discussion_groups#create_discussion_group"
  match "edit_discussion_group/:id" => "discussion_groups#edit_discussion_group"
  match "discussion_groups/delete_discussion_group/:id" => "discussion_groups#delete_discussion_group"
  match "discussion_groups/search_groups/" => "discussion_groups#search_groups"
  match "discussion_groups/add_user_to_groups/:id" => "discussion_groups#add_user_to_groups"
  match "discussion_groups/invite_user_to_groups/:id" => "discussion_groups#invite_user_to_groups"
  match "load_more_groups/:search_text" => "discussion_groups#load_more_groups"
  match "search_for_group/:term" => "users#search_for_group"
  match "notifications/:id" => "discussion_groups#notifications"
  match "accept_invitation/:id" => "discussion_groups#accept_invitation"
  match "decline_invitation/:id" => "discussion_groups#decline_invitation"
  match "join_group/:id" => "discussion_groups#join_group"
  match "unjoin_group/:id" => "discussion_groups#unjoin_group"
  match "leave_joined_group/:id" => "discussion_groups#leave_joined_group"
  match "discussions/load_feeds_by_group/:id" => "discussions#load_feeds_by_group"
  match "load_group_discussion/:id" => "discussions#load_group_discussion"
  match "load_group_discussions_on_scroll/:id" => "discussion_groups#load_group_discussions_on_scroll"

  match "discussion_groups/delete_added_group_user/:id" => "discussion_groups#delete_added_group_user"
  match "discussion_groups/edit_added_group_user/:id" => "discussion_groups#edit_added_group_user"

  match 'discussion_groups/invite_emails_to_group/:id' => 'discussion_groups#invite_emails_to_group'
  match 'discussion_groups/import_gmail_contacts/:id' => 'discussion_groups#import_gmail_contacts'

  resources :discussion_groups do
    collection do
      get 'search_groups'
    end
  end

  match "logins/invitation_sign_up/:id" => "logins#invitation_sign_up"
  resources :users do

app/helpers/discussions_helper.rb
module DiscussionsHelper

   def createCommentsTree(response) #Create Category Tree which is open in new window:
    erg=""
    i=0
    erg +="<div class='inner_comment_wrapper'>
      <div class='float_l'>
        <a class='toggle_comment expand_btn margin_top_five' href='#'>&nbsp;</a>
      </div>
      <div class='float_l'>
        <img alt='' src='images/profile_image.jpg' class='small_user_image' />
      </div>
      <div class='float_l'>
        <div class='comment_detail_div'>
          <a class='user_name' href='#'>#{get_username(response.user_id)}</a>
          <br/><span class='comment_text'>#{response.comment}</span>
          <div class='url_action_div no_left_padding'>
            <img alt='' src='images/rating_stars.jpg' class='ratings'/>
            <span class='comment_count'>[ 23 ] Votes</span>
            <span class='link_seperator float_l'>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;</span> <a class='discussion_action_link' href='#'>Rate It</a>
          </div>
          <div class='post_comment_div'>
            <span class='clear_both'><a class='discussion_action_link response_link' id='#{response.id}' href='#'>Post Comment</a></span>
            <div class='comment_form_div'>
            <form method='post' data-remote='true' action='discussions/post_comment_responses'>
              <textarea class='post_comment_text_area float_l clear_both' id='response_comment_comment'></textarea>
              <input type='hidden' value='#{response.id}' name='response_comment[parent_id]' id='response_comment_parent_id'>
              <input class='blue_btn clear_both float_l' type='submit' value='Post Comment'/>
              <a class='action_link no_text_deco float_l cancel_link' href='#'>Cancel</a>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>"
      if response.children.present?
        erg +="<div class='comments_div' style='display:block;'>"
        response.children.each{|child| erg +="#{createCommentsTree(child)}" }
        erg +="</div>"
      end
    return erg
  end

end

app/views/discussions/_discussions_multiple.html.erb
<% discussions.each do |discussion| %>
    <%= render :partial => "simple_discussion_block", :locals=>{:discussion=>discussion}%>
<% end %>

app/views/discussions/_most_popular_discussion.html.erb
<div class="discussion_block float_r">
  <div class="discussion_header" align="left">
    <span class="green_header padding_left_ten">Most Popular Discussions</span>
  </div>
  <div class="normal_url_block most_pop_discussions">
    <div class="d_inner_div float_l">
      <%= link_to "See all", {:action => "all_discussion"}, {:class => "discussion_action_link"} %>
      <%@most_pop_discussions.each do |discussion|%>
        <%= render :partial => "simple_discussion_block", :locals=>{:discussion=>discussion}%>
      <% end %>
    </div>
    <div class="loader_div" id="most_pop_d_loader">
    <img title="Loading" alt="Loading" src="/images/ajax-loader.gif"/>
  </div>
  </div>
</div>

app/views/discussions/_outer_comment.html.erb
<!-- Outer Comment Start here -->
<%  @other_user.nil? ?  @other_user = current_user : "" %>
<% comment_new = comment %>
<% host_url = "http://"+request.host_with_port %>
<div class="outer_comment_div float_l clear_both <% if @other_user.id==comment.user_id %>current_users_comment<% end %> comment_<%= comment.id %>">
  <div class="float_l">
    <a href="javascript:void(0);" class="toggle_comment <% if comment.children.count>0 %>  expand_btn <%  end %> margin_top_five">&nbsp;</a>
  </div>
  <div class="<%= box_border_shadow_popup(comment) %>">

    <div class="float_l">
      <div class="comment_detail_div">
        <div class="comment_details">
          <% if comment.comment_type=='URL' %>
            <span class="comment_text outer_comment_text">
              <a class="com_title_span" href="<%= comment.comment %>" target="_blank">
                <%= comment.url_title %>
              </a>
            </span>
            <br/>
          <% elsif comment.title.present? %>
            <span class="comment_text outer_comment_text">
              <span class="com_title_span" >
                <%= comment.title if comment.title %>
              </span>
            </span>
            <br/>
          <% end %>
          <span class="clear_both">
            <% att = comment.discussion_attachments.first %>
            <%  if comment.comment_type == "Picture" %>
              <% image = comment.images.first %>
              <% if !image.nil? %>
                <% if image.site_url.present? %>
                  <a target="_blank" href="<%= image.site_url %>" >
                    <img src="<%= comment.images.first.photo(:medium) %>" class="clear_both" style="max-width: 540px;"/>
                  </a>
                <% else %>
                  <img src="<%= comment.images.first.photo(:medium) %>" class="clear_both" style="max-width: 540px;"/>
                <% end %>

              <% end %>
              <span class="clear_both com_comment">
                <%= comment.comment if comment.comment  %>
              </span>
            <% else %>
              <span class="clear_both com_comment"><%= comment.comment if comment.comment_type!="URL" %></span>
              <% att = comment.discussion_attachments.first %>
              <% if !att.nil? && comment.comment_type =="Document" %>
                <a href="<%= host_url+""  %><%= att.file %>" class="<%= att.file_content_type=="application/pdf" ? "pdf_file": "word_file" %> disc_attachment_link clear_both"><%= att.description %></a>
              <% end %>
            <% end %>
            <span class="clear_both">
              by <a href="<%= comment.user.profile_path %>" class="action_link" style="text-decoration:none;font-size: 10px;" title="<%= comment.user.username %>"><%= comment.user.username %></a>
              at <%= comment.created_at %>
            </span>
          </span>
        </div>
        <% unless @login_user.is_admin? %>
          <% if current_user.id == comment.user_id  %>
            <div class="edit_comment_div hidden_element" style="display: none;">
              <%  response_comment = comment %>
              <%= form_for :comment, :url=>{:controller=>:discussions, :action => 'update_comment_responses'}, :remote=>true do |f|  %>
                <select class="comment_type" name="comment[comment_type]" onchange="set_comment_type($(this))">
                  <option value="URL" <%= 'selected' if comment.comment_type=='URL' %>>URL</option>
                  <option value="Comment/Question" <%= 'selected' if comment.comment_type=='Comment/Question' %> >Comment/Question</option>
                  <option value="Document" <%= 'selected' if comment.comment_type=='Document' %>>Document</option>
                  <option value="Picture" <%= 'selected' if comment.comment_type=='Picture' %>>Picture</option>
                </select>
                <input type="hidden" name="com_level" value="outer"/>
                <span class="com_title clear_both discussion_frm_heading">Title:</span>
                <%=  text_field 'comment', 'title', :class=>"float_l comment_title_field",:style=>"width:285px;" ,:maxlength=>"150",:value=>comment.title%>
                <span class="error title_error clear_both float_l"></span>
                <span class="com_Description clear_both discussion_frm_heading">
                  <%= comment.comment_type=="URL" ? "URL" : (comment.comment_type=="Comment/Question" ? "Comment/Question" : "Description") %>:
                </span>
                <%= text_area 'comment','comment', :class=>"post_comment_text_area float_l clear_both" ,:value=>comment.comment%>
                <span class="error url_error clear_both float_l"></span>
                <span id="disc_type_file" class="clear_both <%= comment.comment_type=='Picture' ? '' : 'hidden_element' %>">
                  <span class="picture_options_span <%= comment.comment_type=='Picture' ? '' : 'hidden_element' %>">
                    <a class="pic_options" href="javascript:void(0);" onclick="jQuery(this).closest('#disc_type_file').find('.upld_pic_span').hide();jQuery('#upload_photo_popup').show();pic_form=jQuery(this).closest('form');">Upload Picture</a>
                    <a class="pic_options" href="javascript:void(0);" onclick="show_find_photo_for_comment(jQuery(this));">Find Picture</a>
                  </span>
                  <span class="upld_pic_span clear_both">
                    <input type="file" name="com_file" class="com_file clear_both" />
                    <input type="hidden" name="is_uploaded" id="is_uploaded" value="true"/>
                    <input type="hidden" name="photo_url" value=""/>
                    <input type="hidden" name="added_from" value=""/>
                    <input type="hidden" id="p_id" name="p_id" value="<%=comment.id%>"/>
                  </span>
                  <span class="error file_error clear_both float_l"></span>
                </span>
                <span class="clear_both">&nbsp;&nbsp;&nbsp;</span>

      <%#= text_area 'response_comment', 'comment', :class=>"post_comment_text_area float_l clear_both"%>
                <%= hidden_field_tag 'comment[id]', comment.id %>
                <a class="blue_btn clear_both float_l padding_top_six center_text" onclick='post_comment(jQuery(this));' href="javascript:void(0);">Update</a>
              <% end%>
              <a class="action_link no_text_deco float_l cancel_edit_link comman_cancel_link" href="javascript:void(0);">Cancel</a>
            </div>
          <% end %>
        <% end %>
        <div><%= render :partial=> "discussions/rating_partial", :locals=>{:rating_for => comment} %></div>
        <div class="post_comment_div">
          <span class="clear_both">
            <% unless @login_user.is_admin? %>
              <a href="javascript:void(0);" class="discussion_action_link comment_link clear_both">Post Comment</a>
            <% end %>
            <% if @login_user.is_admin? %>
              <a href="javascript:void(0);" class="discussion_action_link" onclick="delete_comment(jQuery(this),<%= comment.id %>)">Delete</a>
            <% elsif current_user.id == comment.user_id  %>
              <span class="discussion_action_link">&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;</span>
              <a class="discussion_action_link edit_comment_link" href="javascript:void(0);">Edit</a>
              <% if comment.children.count<=0 %>
                <span class="discussion_action_link">&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;</span>
                <a class="discussion_action_link delete_comment_link" onclick="delete_comment(jQuery(this), <%= comment.id %>)" href="javascript:void(0);">Delete</a>
              <% end %>
            <% end %>
          </span>
          <% unless @login_user.is_admin? %>
            <div class="comment_form_div">
              <% form_for :comment, :url=>{:controller=>:discussions, :action => 'post_comment_responses'},:html=>{:class=>"comment_forms",:multipart => true}, :remote=>true do |f|  %>
                <select class="comment_type" name="comment[comment_type]" onchange="set_comment_type($(this))">
                  <option value="URL">URL</option>
                  <option value="Comment/Question">Comment/Question</option>
                  <option value="Document">Document</option>
                  <option value="Picture">Picture</option>
                </select>
                <span class="com_title clear_both discussion_frm_heading">Title:</span>
                <%= text_field 'comment','title', :class=>"float_l comment_title_field",:style=>"width:285px;" ,:maxlength=>"150", :value=>""%>
                <span class="error title_error clear_both float_l"></span>
                <span class="com_Description clear_both discussion_frm_heading">URL:</span>
                <%= text_area 'comment', 'comment', :class=>"post_comment_text_area float_l clear_both", :value=>""%>
                <span class="error url_error clear_both float_l"></span>
                <span id="disc_type_file" class="clear_both hidden_element discussion_frm_heading ">
                  <span class="picture_options_span hidden_element">
                    <a class="pic_options" href="javascript:void(0);" onclick="jQuery(this).closest('#disc_type_file').find('.upld_pic_span').hide();jQuery('#upload_photo_popup').show();pic_form=jQuery(this).closest('form');jQuery('#show_discussion_popup').hide();">Upload Picture</a>
                    <a class="pic_options" href="javascript:void(0);" onclick="show_find_photo_for_comment(jQuery(this));">Find Picture</a>
                  </span>
                  <span class="upld_pic_span clear_both">
                    <input type="file" name="com_file" class="com_file clear_both" />
                    <input type="hidden" name="is_uploaded" id="is_uploaded" value="true"/>
                    <input type="hidden" name="photo_url" value=""/>
                    <input type="hidden" name="added_from" value=""/>
                    <input type="hidden" id="p_id" name="p_id" value="<%=comment_new.id%>"/>
                  </span>
                  <span class="error file_error clear_both float_l"></span>
                </span>
                <span class="clear_both">&nbsp;&nbsp;&nbsp;</span>
                <input type="hidden" name="comment[discussion_id]" value="<%= comment_new.discussion_id %>"/>
                <%= hidden_field_tag 'comment[parent_id]', comment_new.id %>
                <a class="blue_btn clear_both float_l padding_top_six center_text" onclick='post_comment(jQuery(this));'>Post Comment</a>
              <% end %>
              <!--<%= form_for :response_comment, :url=>{:controller=>:discussions, :action => 'post_comment_responses'}, :remote=>true do |f|  %>
                <%= text_area 'response_comment', 'comment', :class=>"post_comment_text_area float_l clear_both"%>
                <%= hidden_field_tag 'response_comment[discussion_id]', comment.discussion_id %>
                <%= hidden_field_tag 'response_comment[parent_id]', comment.id %>
                                                         <a class="blue_btn clear_both float_l padding_top_six center_text" onclick='post_comment_response(jQuery(this));'>Post Comment</a>
              <% end%>-->
              <a class="action_link no_text_deco float_l cancel_link comman_cancel_link" href="javascript:void(0);">Cancel</a>
            </div>
          <% end %>
        </div>
      </div>
    </div></div>
  <!-- Comments start here -->
  <div class="comments_div grey_bg">
    <%  comment.children.each do |response| %>
      <%= render :partial=>"discussions/inner_comment", :locals=>{:response=>response,:is_creating=>false} %>
    <% end %>
  </div>
  <!-- Comments end here here -->
</div>
<!-- Outer Comment ends here -->

<%# if is_creating %>
<script type="text/javascript">
  jQuery(document).ready(function(){
    set_effects();
  });
</script>
<%# end %>

app/views/discussions/_rating_partial.html.erb
<!-- Ref:- http://eighty-b.tumblr.com/post/1569674815/creating-an-ajaxified-star-rating-system-in-rails-3 
           https://github.com/azabaj/acts_as_rateable 
           http://www.wbotelhos.com/raty/
-->

<% rating_class = rating_for.class == Comment ? "comment" : (rating_for.class == Discussion ? "discussion" : "picture" )
   my_rating = rating_for.rated_by?(@login_user) %>

<!--User can't rate there own discussions/comments -->

<div class="url_action_div no_left_padding" >
  <div class="rating_container"><span class="hidden_element"><%= rating_for.average_rating %></span><div id="click" class="rating_class_fixed"></div></div>
  <span class="comment_count">[ <%= rating_for.votes %> ] Votes</span>
  <% unless @login_user.is_admin? %>
 
      <span class="link_seperator float_l">&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;</span>
      <a class="discussion_action_link show_rate_it" href="javascript:void(0)" >Rate It</a>
      <div class="hidden_element">
      <% if my_rating %>
        <div class="rating_container"><span class="hidden_element"><%= my_rating.rate.score %></span><div id="click" class="rating_class_fixed"></div></div>
      <% else %>
            <% form_tag("/users/#{rating_for.id}/rate", :remote => true, :html => { :class => 'rating_ballot' }) do |f| %>
              <div id="click" class="rating_class"></div>
              <%= hidden_field_tag("rating_for_id", rating_for.id) %>
            <%= hidden_field_tag("rating_for_class", rating_class) %>
          <% end %>
      <% end %>
      </div>

  <% end %>
</div>

app/views/discussions/create_discussion.js.erb
<% if @message=="Discussion posted successfully."  %>
  <% if @current_page %>

    jQuery("#discussion_title").val('');
    jQuery("#discussion_discussion").val('');
    jQuery('#discussion_form input:text,#discussion_form input:file, #discussion_form textarea, #discussion_form input[name="photo_url"]').val('');
    var $items = jQuery("<%= escape_javascript(render :partial => "discussions/simple_discussion_block", :locals=>{:discussion=>@lastest_discussion}).html_safe %>");
    jQuery(".normal_url_block .d_inner_div").prepend($items)
    apply_ratings();
  <% else %>
    jQuery(".no_disc_in_group").html('');
    jQuery('#discussion_form input:text,#discussion_form input:file, #discussion_form textarea, #discussion_form input[name="photo_url"]').val('');
    var $items = jQuery("<%= escape_javascript(render :partial => "discussion_groups/simple_discussion_groups_block", :locals=>{:discussion=>@lastest_discussion}).html_safe %>");
    jQuery("#result").prepend($items).masonry( 'appended', $items, true );
    setTimeout('jQuery("#result").masonry( "reload" );',500);
  <% end %>
<% end %>
  display_flash_message("<%= escape_javascript(@message).html_safe %>");


jQuery(".dis_attachment_container").html("");
set_effects();

is_sending = false;

app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/load_more_feeds.js.erb
<% if @feeds.blank? %>
  //jQuery("#feeds_loader").hide();
  //feed_finish();
<% else %>
  var $output_html = jQuery("<%= escape_javascript(render :partial=>"feeds", :locals=>{:feeds => @feeds}).html_safe %>");

  //
  $output_html.find(".show_rate_it").click(function(){
            jQuery(this).next().toggle();
  jQuery(this).text(jQuery(this).text() == 'Rate It' ? 'Cancel' : 'Rate It');
          });

  $output_html.find('.show_rate_it').bind("click" , function() {
        jQuery(this).next().toggle();
        jQuery(this).text(jQuery(this).text() == 'Rate It' ? 'Cancel' : 'Rate It');
      });

  $output_html.find('.rating_class').raty({
                          click: function(score, evt) {
                                  current_object = jQuery(this);
                                  $(this).parent().submit();
                          }
                  });


  $output_html.find(".rating_container").each(function(v,i){
          var value = jQuery(this).children("span").html();
  if(!jQuery(this).children('.rating_class_fixed').children("img").size()>0)
  {
  jQuery(this).children('.rating_class_fixed').raty({
                                          readOnly:	true,
                                          start:		value
                                  });
  }

  });
  jQuery(".feeds_block .d_inner_div").append($output_html);
  set_effects();
<% end %>

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @discussion.url %>
</p>


<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
<%= link_to 'Back', discussions_path %>