config/routes.rb
FavTabs::Application.routes.draw do

  constraints(:host => "www.convorum.com") do
    match "(*x)" => redirect { |params, request|
      URI.parse(request.url).tap { |x| x.host = "convorum.com" }.to_s
    }
  end 
  match "discussions/create_multiple_discussion"  => "discussions#create_multiple_discussion"
  match "discussion_groups/create_multiple_discussion"  => "discussion_groups#create_multiple_discussion"
  match "discussions/post_multiple_comments"  => "discussions#post_multiple_comments"
  match "discussions/save_multiple_comments"  => "discussions#save_multiple_comments"
  resources :albums

  resources :profile_pictures

  resources :ratings

  resources :comments

  resources :user_discussions

  resources :follower_followings
  match "discussions/updates_from_following_follower" => "discussions#updates_from_following_follower"
  resources :messages
  match 'new_message' => 'messages#new_message'
  match 'sent_messages' => 'messages#sent_messages'
  match 'message_delete' => 'messages#message_delete'
  match 'from_follower_following' => 'messages#from_follower_following'
  resources :tab_sites

  resources :tabs

  resources :user_details
  match 'logins/create' => 'logins#create'
  match 'logins/activate/:id' => 'logins#activate'
  match 'logins/forgot_password' => 'logins#forgot_password'
  match 'login' => 'logins#login'
  match 'logout' => 'logins#logout'
  match 'test_remote_call' => 'users#test_remote_call'

  match 'users/edit_profile_picture' => 'users#edit_profile_picture'
  match 'load_more_search_result' => 'users#load_more_search_result'

  match 'about_us' => 'logins#about_us'
  match 'contact_us' => 'logins#contact_us'

  match "users/profile/:id"  => "users#my_account"

  match 'users/followers/:id' => 'users#followers'
  match 'users/followings/:id' => 'users#followings'
  match 'users/follow/:id' => 'users#follow'
  match 'users/set_email_updates/:id' => 'users#set_email_updates'
  match 'follower_following_delete/:id' => 'users#follower_following_delete'

  match "users/add_tab"  => "users#add_tab"
  match "users/add_current_tab"  => "users#add_current_tab"
  match "users/edit_tab"  => "users#edit_tab"
  match "users/delete_tab"  => "users#delete_tab"
  match "users/delete_site_url"  => "users#delete_site_url"
  match "users/edit_site_url"  => "users#edit_site_url"
  match "users/create_site"  => "users#create_site"
  match "users/find_people" => "users#find_people"
  match "users/manage_groups" => "users#manage_groups"
  match "users/create_group" => "users#create_group"
  match "users/edit_group" => "users#edit_group"
  match "users/add_email" => "users#add_email"
  match "users/add_email_to_crowd/:id" => "users#add_email_to_crowd"
  match "users/import_gmail_contacts/:id" => "users#import_gmail_contacts"

  match "users/delete_group" => "users#delete_group"

  match "albums/create_album" => "albums#create_album"
  match "albums/edit_album" => "albums#edit_album"
  match "albums/delete_album/:id" => "albums#delete_album"
  match "share_album_in_group/:id" => "albums#share_album_in_group"
  match "share_photo_in_group/:id" => "albums#share_photo_in_group"
  match "albums/create_multiple_photos" => "albums#create_multiple_photos"
  match "albums/save_multiple_photos" => "albums#save_multiple_photos"

  match "find_photo" => "albums#find_photo"
  match "add_photo" => "albums#add_photo"
  match "add_photos_from_site" => "albums#add_photos_from_site"
  match "load_my_groups" => "albums#load_my_groups"
  match "add_photo_from_system" => "albums#add_photo_from_system"
  match "load_photos_discussions" => "albums#load_photos_discussions"
  match "load_album_photos/:id" => "albums#load_album_photos"
  
  match "users/set_tab_private/:id"  => "users#set_tab_private"
  match "users/set_tab_public/:id"  => "users#set_tab_public"
  match "share_with_group/:id"  => "users#share_with_group"
  match "add_to_group/:id"  => "users#add_to_group"
  match "non_site_add_to_crowd/:id"  => "users#non_site_add_to_crowd"

  match "remove_from_group/:id"  => "users#remove_from_group"
  match "remove_non_site_from_crowd/:id"  => "users#remove_non_site_from_crowd"
  
  resources :discussions
  match "discussions/create_discussion"  => "discussions#create_discussion"

  match "discussions/add_title_discription"  => "discussions#add_title_discription"
  match "discussions/add_title_discription/:id"  => "discussions#add_title_discription"
  match "discussions/save_multiple_discussion"  => "discussions#save_multiple_discussion"
  match "discussions/return_to_previous/:id"  => "discussions#return_to_previous"
  match "discussions/updates_from_following_follower" => "discussions#updates_from_following_follower"
  match "discussions/post_comments"  => "discussions#post_comments"
  match "discussions/join_discussion/:id"  => "discussions#join_discussion"
  match "load_comments/:id"  => "discussions#load_comments"
  match "load_my_comments/:id"  => "discussions#load_my_comments"
  match "load_my_discussions/:id"  => "discussions#load_my_discussions"
  match "load_my_discussions_on_scroll"  => "discussions#load_my_discussions_on_scroll"
  match "load_most_pop_discussions_on_scroll"  => "discussions#load_most_pop_discussions_on_scroll"

  match "discussions/web_content/:id"  => "discussions#web_content"

  match "discussions/post_multiple_comment_responses"  => "discussions#post_multiple_comment_responses"
  match "discussions/post_comment_responses"  => "discussions#post_comment_responses"
  match "all_discussion" => "discussions#all_discussion"
  match "all_discussion" => "discussions#all_discussion"
  match "load_discussion_as_per_time/:id" => "discussions#load_discussion_as_per_time"
  match "discussions/update_comment_responses" => "discussions#update_comment_responses"
  match "delete_comment/:id" => "discussions#delete_comment"
  match "delete_discussion/:id" => "discussions#delete_discussion"
  match "search_user_names_for_message/:term" => "users#search_user_names_for_message"
  match "show_discussion/:id" => "discussions#show_discussion"
  match "load_my_comments_on_scroll" => "discussions#load_my_comments_on_scroll"
  match "load_more_feeds" => "discussions#load_more_feeds"

  match "albums/index/:id"  => "albums#index"
  match "find_photo" => "albums#find_photo"
  match "add_photo" => "albums#add_photo"
  match "add_photos_from_site" => "albums#add_photos_from_site"
  match "load_my_groups" => "albums#load_my_groups"
  match "load_photo_full_detail/:id" => "albums#load_photo_full_detail"
  match "like_picture/:id" => "albums#like_picture"
  match "unlike_picture/:id" => "albums#unlike_picture"
  match "delete_picture/:id" => "albums#delete_picture"
  match "post_photo_comment" => "albums#post_photo_comment"
  match "delete_picture_comment/:id" => "albums#delete_picture_comment"
  match "import_picture/:id" => "albums#import_picture"
  match "photo_discussions" => "albums#photo_discussions"
  match "upload_photos" => "albums#create_multiple_albums"

  match "discussion_groups/import_picture/:id" => "discussion_groups#import_picture"
  match "discussion_groups/delete_picture/:id" => "discussion_groups#delete_picture"
  match "discussion_groups/delete_picture_comment/:id" => "discussion_groups#delete_picture_comment"
  match "discussion_groups/post_photo_comment" => "discussion_groups#post_photo_comment"
  match "discussion_groups/load_photo_full_detail/:id" => "discussion_groups#load_photo_full_detail"
  match "discussion_groups/load_pictures/:id" => "discussion_groups#load_pictures"
  match "discussion_groups/like_picture/:id" => "discussion_groups#like_picture"
  match "discussion_groups/unlike_picture/:id" => "discussion_groups#unlike_picture"
  match "discussion_groups/add_photo_from_system" => "discussion_groups#add_photo_from_system"
  match "discussion_groups/add_photo" => "discussion_groups#add_photo"
  match "discussion_groups/group_album/:id" => "discussion_groups#group_album"
  match "discussion_groups/create_discussion" => "discussion_groups#create_discussion"
  match "discussion_groups/create_discussion_group" => "discussion_groups#create_discussion_group"
  match "edit_discussion_group/:id" => "discussion_groups#edit_discussion_group"
  match "discussion_groups/delete_discussion_group/:id" => "discussion_groups#delete_discussion_group"
  match "discussion_groups/search_groups/" => "discussion_groups#search_groups"
  match "discussion_groups/add_user_to_groups/:id" => "discussion_groups#add_user_to_groups"
  match "discussion_groups/invite_user_to_groups/:id" => "discussion_groups#invite_user_to_groups"
  match "load_more_groups/:search_text" => "discussion_groups#load_more_groups"
  match "search_for_group/:term" => "users#search_for_group"
  match "notifications/:id" => "discussion_groups#notifications"
  match "accept_invitation/:id" => "discussion_groups#accept_invitation"
  match "decline_invitation/:id" => "discussion_groups#decline_invitation"
  match "join_group/:id" => "discussion_groups#join_group"
  match "unjoin_group/:id" => "discussion_groups#unjoin_group"
  match "leave_joined_group/:id" => "discussion_groups#leave_joined_group"
  match "discussions/load_feeds_by_group/:id" => "discussions#load_feeds_by_group"
  match "load_group_discussion/:id" => "discussions#load_group_discussion"
  match "load_group_discussions_on_scroll/:id" => "discussion_groups#load_group_discussions_on_scroll"

  match "discussion_groups/delete_added_group_user/:id" => "discussion_groups#delete_added_group_user"
  match "discussion_groups/edit_added_group_user/:id" => "discussion_groups#edit_added_group_user"

  match 'discussion_groups/invite_emails_to_group/:id' => 'discussion_groups#invite_emails_to_group'
  match 'discussion_groups/import_gmail_contacts/:id' => 'discussion_groups#import_gmail_contacts'

  resources :discussion_groups do
    collection do
      get 'search_groups'
    end
  end

  match "logins/invitation_sign_up/:id" => "logins#invitation_sign_up"
  resources :users do

app/models/discussion_group.rb
class DiscussionGroup < ActiveRecord::Base
  belongs_to :user
  has_many :discussion_group_discussions, :dependent => :destroy
  has_many :discussion_group_users, :dependent => :destroy
  has_many :non_site_users, :as => :invitable, :dependent => :destroy
  has_many :images, :as => :imageable, :dependent => :destroy
  has_many :discussions, :through => :discussion_group_discussions
  scope :join_group_user, select("dg.*").joins("dg LEFT JOIN discussion_group_users dgu ON dg.id=dgu.discussion_group_id ").order("dg.name")
  scope :public_member, lambda{ |id| where(["((dg.is_public=? OR dg.is_public=?) AND dgu.user_id=? AND dgu.is_member=?)", true, false, id, true ]) }
  

  validates :name, :presence => {:message => "Group name can't be blank."}, :length => {:maximum => 40}, :uniqueness => {:scope => :user_id}
  validates :description, :presence => {:message => "Group description can't be blank."}, :length => {:maximum => 1000, :message => "Maximum 1000 characters are allowed."}
  #validates :is_public, :presence => {:message => "Please select a privacy option."}

  #--
  #
  #Created on: 04/03/2012
  #Purpose:
  #++ This method is used to find all discussions of that group
  def all_discussions
    Discussion.join_group.group_share_type(self.id, "groups")
  end

  #--
  #
  #Created on: 04/03/2012
  #Purpose:
  #++ This method is used to find all discussions of that group
  def all_group_discussions(page)
    per_page = 20
    off = (page-1)*per_page
    Discussion.join_group.group_share_type(self.id, "groups").limit(per_page).offset(off)
  end

  #--
  #
  #Created on: 06/03/2012
  #Purpose:
  #++ This method is used to find all group users
  def group_users
    DiscussionGroupUser.where("discussion_group_id=? AND is_member=?", self.id, true)
  end

end

app/helpers/discussion_groups_helper.rb
module DiscussionGroupsHelper

  def box_border_shadow(discussion)
    str = "discussions"
    
    if discussion.discussion_type == "URL"
      str = "discussions"
    elsif discussion.discussion_type == "Picture"
      str = "disc_with_picture"
    else
      str = "commments_questions"
    end

    discussion.discussion_attachments.each do |att_file|
      if att_file.file_content_type == "application/pdf"
        str = "disc_with_pdf"
      elsif att_file.file_content_type == "application/msword"
        str = "disc_with_doc"
      end
    end if discussion.discussion_type == "Document"
    str
  end

  def box_border_shadow_popup(obj)
    type = obj.class == Discussion ? obj.discussion_type : obj.comment_type
    str = ""
    str = case type
            when 'URL' then 'user_gray_border'
            when 'Picture' then 'user_green_border'
            else 'user_yellow_border'
           end
    att_file = obj.discussion_attachments.first
    if att_file.file_content_type == "application/pdf"
      str = "user_red_border"
    elsif att_file.file_content_type == "application/msword"
      str = "user_blue_border"
    end if att_file && type == "Document"
    str
  end

end

app/views/discussion_groups/_accept_group_invitation.html.erb
<div class="grey_overlay" id="accept_invitation_to_group_user">
  <div class="pop_up" >
    <div class="popup_inner_div">
      <a href="javascript:void(0);" onclick="jQuery('#accept_invitation_to_group_user').fadeOut();" class="popup_close_btn">&nbsp;</a>
      <div class="popup_content">
        <span class="popup_heading"></span>
          <table width="100%" class="popup_form_table">
            <tr>
              <td  align="left" colspan="2">
                <span class="font_for_message_display form_field_name">You are successfully added to the <%= group.discussion_group.name %> group. To visit the group <%= group.discussion_group.name %> please 
                <span class="form_field_link"><%= link_to "Click here", {:action => 'show', :id => group.discussion_group.id}, :class => "accept_to_notify_link"  %>&nbsp;<span class="accept_or_cancel">or</span>
                <a href="javascript:void(0);" onclick="jQuery('#accept_invitation_to_group_user').fadeOut();" class = "accept_to_notify_link" >Cancel</a>
                </span>
		</span>
              </td>
            </tr>
          </table>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#accept_invitation_to_group_user .pop_up").center();
  });
    jQuery('#accept_invitation_to_group_user').show();
</script>

app/views/discussion_groups/_form.html.erb
<%= form_for(@discussion_group) do |f| %>
  <% if @discussion_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion_group.errors.count, "error") %> prohibited this discussion_group from being saved:</h2>

      <ul>
      <% @discussion_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discussion_groups/_private_group_added_users.html.erb
<div class="group_mem_container" id="private_group_nsu">
  <span class="green_header">Added Users</span>
  <div class="grp_members_outer_div">
    <% non_ste_users = group.non_site_users.where("invitation_type='Added'") %>
    <div style="width:<%= non_ste_users.length*70 %>px;">
      <% non_ste_users.each do |nsu| %>
        <div class="user_pic_2 follower_following_img_block" style="padding: 5px;">
          <a href="javascript:void(0);">
            <img class="medium_user_image" src="/images/profile_image.jpg" title="<%= nsu.email %>"/>
          </a>
          <span>
            <%= link_to "Edit", {:controller=>:discussion_groups, :action=>:edit_added_group_user,:id=>nsu.id}, :remote=>true, :class=>"edit_nsu action_link" %>
            <%= link_to image_tag("/images/cross-icon.png", :style=>"height: 10px;width: 10px;"), {:controller=>:discussion_groups, :action=>:delete_added_group_user,:id=>nsu.id}, :confirm=>"Are you sure you want to remove?",:remote=>true, :class=>"delete_nsu",:title=>"Remove" %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
  <script type="text/javascript">
    jQuery(function(){
      jQuery('.delete_nsu').bind('ajax:success',  function(evt, data, status, xhr){
        if(data=="Success")
        {
          jQuery(this).closest(".follower_following_img_block").fadeOut("slow").remove();
          display_flash_message("User not removed. Please try again.");
        }
        else
        {
          display_flash_message("User not removed. Please try again.");
        }
      }).bind("ajax:error", function(evt, data, status, xhr){
        //console.log(data)
        if(data.responseText=="Success")
        {
          jQuery(this).closest(".follower_following_img_block").fadeOut("slow").remove();
          display_flash_message("User removed successfully from group.");
        }
        else
        {
          display_flash_message("User not removed. Please try again.");
        }
        
      });
      jQuery('.edit_nsu').bind('ajax:success',  function(evt, data, status, xhr){
        jQuery("body").append(jQuery(data));
        jQuery(".pop_up").center();

      }).bind("ajax:error", function(evt, data, status, xhr){
        //console.log(data)responseText==
        jQuery("body").append(jQuery(dataresponseText));
        jQuery(".pop_up").center();
      });
    });
  </script>
</div>

app/views/discussion_groups/_upload_des_photo.html.erb
<div class="grey_overlay" id="upload_des_photo_popup">
  <div class="upload_pop_up" >
    <div class="popup_inner_div">
      <a href="javascript:void(0);" onclick="jQuery('#upload_des_photo_popup').hide();jQuery('#show_discussion_popup').show();cur_popup.show();" class="popup_close_btn">&nbsp;</a>
      <div class="upload_popup_content">
        <span class="popup_heading">Upload Photo</span><br/><br/>
        <div id="find_photo_form" class="photo_form" style="display: block;">
         
		
<form id="fileupload" >
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="span7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span><%= t('fileupload.add_files') %></span>
                    <%#= f.file_field :path %>
		    <input id="picture_path" name="picture[path]" type="file" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span><%= t('fileupload.start_upload') %></span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span><%= t('fileupload.cancel_upload') %></span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="icon-trash icon-white"></i>
                    <span><%= t('fileupload.delete_multi') %></span>
                </button>
                <input type="checkbox" class="toggle">
            </div>
           
        </div>
        <!-- The loading indicator is shown during image processing -->
        <div class="fileupload-loading"></div>
        <br>
        <!-- The table listing the files available for upload/download -->
        <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
        </table>
    </form>
<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>

<%= render "discussion_groups/fileupload/queue" %>

<%= render "discussion_groups/fileupload/index" %>

<%= render "discussion_groups/fileupload/js_include_local" %>


        </div>
      </div>
    </div>
  </div>
</div>
<style>
.close_pop_btn{
	position: absolute;
	top: 38px;
	left: 123px;
	background:url(/images/popup_close_btn.png) no-repeat;
	border:none;
	cursor:pointer;
}
.cancel_text{
	width:20px;
	opacity:0;
}
.image_block{
	position:relative;
}
.template-upload{
	margin:0 5px;
}
.template-upload input[type="text"]{
	height:20px;
	width:140px;
}
.template-upload textarea{
	height:50px;
	width:140px;
}
.fade_align{
	height:150px;
	display:block;
	width: 150px;
	border:1px solid #ccc;
}
.cancel_x{
	position:absolute;
}
</style>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#upload_des_photo_popup .upload_pop_up").css({"position":"fixed","top":(jQuery(window).height()-jQuery("#upload_des_photo_popup .upload_pop_up").height())/2+"px"});
    jQuery("#upload_des_photo_popup .upload_pop_up").css({"position":"fixed","left":(jQuery(window).width()-jQuery("#upload_des_photo_popup .upload_pop_up").width())/2+"px"});
  });
  var url="";
  function check_photo_url(mode)
  {
    jQuery(".form_error").html("");
    var url ="";
    if(mode=="prev")
    {
      url = jQuery("#site_url_prev").val();
      if(url !="" && !url.match(/^(ht|f)tps?:\/\//))
      {
        url = "http://"+url;
        jQuery("#site_url_prev").val(url);

      }
    }
    else
    {
      url= jQuery("#photos_site_url").val();
      if(url !="" && !url.match(/^(ht|f)tps?:\/\//))
      {
        url = "http://"+url;
        jQuery("#photos_site_url").val(url);

      }
    }
    var decode_url = url;
    var flag = true;
    var tabRegExp = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/;
    if(jQuery.trim(url).length==0)
    {
      flag = false;
      jQuery(".siteurlError").html("Please enter site url.");
    }
    else
    {
      if(!url.match(tabRegExp))
      {
        flag = false;
        jQuery(".siteurlError").html("Please enter valid site url.");
      }
    }
    if(flag)
    {
      toggle_ajax_loader();
      var original_url = url;
      url = encodeURIComponent(url);
      jQuery.get("<%= url_for :controller=>:albums,:action => 'find_photo',:only_path => false %>?site_url="+url,function(data){

        $rem_html = jQuery(data);
        var is_found = false;
        jQuery("#upload_photo_popup").fadeOut(function(){
          $images= jQuery("<div class='rem_ph_div'></div>");
          $rem_html.find("img").each(function(v,i){
            if(jQuery(this).attr("src") != undefined)
            {
              var newImg = new Image();

              $image = jQuery("<img src='"+jQuery(this).attr('src')+"' />")
              if((!jQuery(this).attr("src").match("http://")) && !jQuery(this).attr("src").match("data:image"))
              {
                var l= decode_url;
                l = l.substr(0,l.indexOf("/",10));
                l = l=="" ? decode_url+"/" : l;
                src_n = $image.attr("src")
                src_n = src_n.replace('..',"");
                src_n = src_n.match("^/") ? src_n : "/"+src_n;
                $image.attr("src",l+src_n);
              }
              if(decode_url.match("http://www.google.co.in") || jQuery.browser.safari || jQuery.browser.opera)
              {
                $images.append($image);
                is_found = true;
              }
              else
              {
                  $images.append($image);
                  is_found = true;
              }
            }

          });
          toggle_ajax_loader();
          if(is_found)
          {

            jQuery("#show_remote_photos div.rem_ph_div").replaceWith($images);
            jQuery("#show_remote_photos div.rem_ph_div img:first").addClass("current");
            jQuery("#photo_url_field").val(jQuery("#show_remote_photos div.rem_ph_div img:first").attr('src'));
            jQuery("#site_url_prev ,#site_url_for_sitename").val(original_url);
            jQuery("#add_remote_phot_submit").val("Add");
            jQuery("#show_remote_photos").fadeIn();
          }
          else
          {
            display_flash_message("No useful image found.");
          }
        });
      });
    }
    return false;
  }
</script>

app/views/discussion_groups/accept_invitation.js.erb
<% if @accept %>
  var $result = jQuery("<%= escape_javascript(render :partial => "accept_group_invitation", :locals=>{:group=>@accept}).html_safe %>");
  jQuery('body').append($result);
  jQuery('#accept_invitation_to_group_user').show();
  jQuery("#group_invition_<%= @accept.id %>").fadeOut().remove();
  <% if  !DiscussionGroupUser.where("discussion_group_id=? AND is_member=?", @accept.id, false).present? %>
    jQuery('#search_result_for_group_error').html('There are no invitations available for you.');
  <% end %>
<% else %>
  display_flash_message("<%= @notice %>");
<% end %>

app/views/discussion_groups/delete_discussion_group.js.erb
jQuery("#disc_group_block_<%= @discussion_group.id %>").fadeOut().remove();
<% if @login_user.all_public_private_groups.blank? %>
  jQuery('#no_disc_group_error').html('There are no groups available for you.');
<% end %>

app/views/discussion_groups/delete_picture_comment.js.erb
var com_count = <%= @pic.comment_count %>;
jQuery(".photo_comment_<%= params[:id] %>").fadeOut(function(){jQuery(this).remove();jQuery(".photos_container").masonry( 'reload');});
jQuery(".pic_comment_count_<%= @pic.id %>").html(com_count);
jQuery(".photos_container").masonry( 'reload');

app/views/discussion_groups/edit_discussion_group.js.erb
var output_html = ("<%= escape_javascript(@discussion_group.name).html_safe %>");
jQuery("#edit_disc_group_popup").fadeOut(function(){
 <% if @discussion_group.errors.blank? %>
   jQuery("#discussion_group_name<%= @discussion_group.id%>").html(output_html);
 <% end %>
  display_flash_message("<%= escape_javascript(@notice).html_safe %>");
}).remove();
jQuery("#group_disc_name_edit_<%= @discussion_group.id %>").html("<%= @discussion_group.name %>")

is_sending = false;

app/views/discussion_groups/invite_user_to_groups.js.erb
<% if @discussion_group.id %>
jQuery('#invite_group_user_email_error').html('');
  var $output_html = jQuery("<%= escape_javascript(render :partial => "group_block", :locals=>{:disc_group => @discussion_group}).html_safe %>");
  jQuery("#public_group_user").fadeOut(function(){
    jQuery("#groups_container").append($output_html);
    $output_html.hover(function(){
      jQuery(this).find(".album_actions").show().animate({'height':'15px'},"fast");
    },function(){
      jQuery(this).find(".album_actions").animate({'height':'0px'},"fast",function(){jQuery(this).hide()});
    });
  });
  <% end %>
display_flash_message("<%= escape_javascript(@notice).html_safe %>");
is_sending = false;

app/views/discussion_groups/like_picture.js.erb
var $new_link = jQuery("<%= escape_javascript(link_to 'Unlike', {:action => 'unlike_picture', :id => params[:id] }, :remote=>true, :class => "album_action_link float_l like_link_#{params[:id]}").html_safe %>");
jQuery(".like_link_"+<%= params[:id] %>).replaceWith($new_link);
var $user = jQuery('<a href="<%= @login_user.profile_path %>" class="liker_<%= @login_user.id %>"><img src="<%= @login_user.profile_pic(:small) %>" class="small_user_image float_l" title="<%= @login_user.username %>" /></a>');
jQuery(".photos_likers_container_<%= params[:id] %>").append($user);
var l_count = <%= @pic.like_count %>;
 jQuery(".pic_count_<%= params[:id] %>").html(l_count)

app/views/discussion_groups/load_more_groups.js.erb
var $output_html = jQuery("<%= escape_javascript(render :partial => "groups_multiple", :locals=>{:discussion_groups=>@discussion_groups}).html_safe %>");
jQuery(".d_grp_conatiner").append($output_html);
jQuery(".group_loader_div").hide();
<%  if @discussion_groups.blank? %>
 finish= false;
<% end %>

app/views/discussion_groups/new.html.erb
<h1>New discussion_group</h1>

<%= render 'form' %>

<%= link_to 'Back', discussion_groups_path %>